version: "3"
services:
  database:
    image: postgres:12-alpine
    container_name: supplyradar-db
    hostname: supplyradar-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=supplyradar